export const HABIT_LIST_REQUEST = 'HABIT_LIST_REQUEST'
export const HABIT_LIST_SUCCESS = 'HABIT_LIST_SUCCESS'
export const HABIT_LIST_FAIL = 'HABIT_LIST_FAIL'


export const HABIT_UPDATE_REQUEST ='HABIT_UPDATE_REQUEST'
export const HABIT_UPDATE_SUCCESS ='HABIT_UPDATE_SUCCESS'
export const HABIT_UPDATE_FAIL='HABIT_UPDATE_FAIL'
export const HABIT_UPDATE_RESET='HABIT_UPDATE_RESET'


export const HABIT_CREATE_REQUEST ='HABIT_CREATE_REQUEST'
export const HABIT_CREATE_SUCCESS ='HABIT_CREATE_SUCCESS'
export const HABIT_CREATE_FAIL='HABIT_CREATE_FAIL'
export const HABIT_CREATE_RESET='HABIT_CREATE_RESET'
